// Auto-generated by scripts/generate-story-entries.js
module.exports = {
	modules: {
		'./Choptima/ChoptimaAssembly.stories.tsx': require('../components/Choptima/ChoptimaAssembly.stories.tsx'),
		'./Text/Text.stories.tsx': require('../components/Text/Text.stories.tsx'),
	},
}
