/* do not change this file, it is auto generated by storybook. */
import { start, updateView, type View } from '@storybook/react-native'

import '@storybook/addon-ondevice-controls/register'
import '@storybook/addon-ondevice-actions/register'

const normalizedStories = [
	{
		titlePrefix: '',
		directory: './components',
		files: '**/*.stories.@(js|jsx|ts|tsx)',
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$/,
		// @ts-expect-error
		req: require.context(
			'../components',
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$/,
		),
	},
	{
		titlePrefix: '',
		directory: './components',
		files: '**/*.stories.tsx',
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$/,
		// @ts-expect-error
		req: require.context(
			'../components',
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$/,
		),
	},
]

declare global {
	var view: View
	var STORIES: typeof normalizedStories
}

const annotations = [
	require('./preview'),
	require('@storybook/react-native/preview'),
]

global.STORIES = normalizedStories

// @ts-expect-error
module?.hot?.accept?.()

if (!global.view) {
	global.view = start({
		annotations,
		storyEntries: normalizedStories,
	})
} else {
	updateView(global.view, annotations, normalizedStories)
}

export const view: View = global.view
